version: "3"

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./node/.docker/mysql:/var/lib/mysql
      - ./node/config/database:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet

  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: app
    restart: always
    entrypoint: wait-for db:3306 -t 40 -- ./start.sh
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db
    networks:
      - nodenet

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - db
      - app
    networks:
      - nodenet

networks:
  nodenet:
    driver: bridge
